version: "3.9"

services:
  
  mysql:
    image: mysql:5.6
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: genesysjp
      MYSQL_DATABASE: INFINITCOMERCIAL
      MYSQL_ROOT_HOST: "%"
      TZ: America/Sao_Paulo
    ports:
      - 3366:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - dbnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db_sqlserver
    restart: always
    environment:
      SA_PASSWORD: "Strong@123" # senha do administrador
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - ./data/sqlserver:/var/opt/mssql
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge
