version: "3.9"

services:
  
  mysql:
    image: mysql:8
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: genesysjp
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_HOST: "%"
      TZ: America/Sao_Paulo
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - dbnet


networks:
  dbnet:
    driver: bridge